-- report -  Total revenue generated by each Aircraft type

DELIMITER $$

CREATE FUNCTION Revenue_By_Aircraft_Type(aircraft_model VARCHAR(50))
RETURNS DOUBLE
DETERMINISTIC
BEGIN
    DECLARE total_revenue DOUBLE DEFAULT 0;

    SELECT
        SUM(b.total_amount)
    INTO
        total_revenue
    FROM
        Aircraft a
    JOIN
        Model m ON a.model = m.model
    JOIN
        Flight f ON a.aircraft_id = f.aircraft_id
    JOIN
        Booking b ON f.flight_id = b.flight_id
    WHERE
        m.model = aircraft_model;

    RETURN total_revenue;
END $$

DELIMITER ;


-- report -  Given a date range, number of passengers travelling to a given destination

DELIMITER $$

CREATE FUNCTION passenger_count_by_destination(
    destination_code CHAR(3),
    start_date DATE,
    end_date DATE
)
RETURNS INT
DETERMINISTIC
BEGIN
    DECLARE passenger_count INT DEFAULT 0;

    SELECT
        COUNT(DISTINCT b.passenger_id)
    INTO
        passenger_count
    FROM
        Booking b
    JOIN
        Flight f ON b.flight_id = f.flight_id
    JOIN
        Route r ON f.route_id = r.route_id
    WHERE
        r.destination_code = destination_code
        AND f.departure BETWEEN start_date AND end_date;

    RETURN passenger_count;
END $$

DELIMITER ;
