import React, { useState, useEffect } from 'react';
import { Table, message } from 'antd'; 
import axios from '../axiosConfig.js';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts'; 

export default function Report5Content() {
  const [revenueData, setRevenueData] = useState([]); // State to hold revenue data

  useEffect(() => {
    // Fetch revenue data on component mount
    const fetchRevenueData = async () => {
      try {
        const response = await axios.get('/admin/revenue-by-aircraft-type');
        setRevenueData(response.data); // Update the revenue data state
      } catch (err) {
        console.error("Error fetching revenue data:", err);
        message.error("Failed to fetch revenue data");
      }
    };

    fetchRevenueData(); // Fetch revenue data
  }, []);

  
  const revenueColumns = [
    {
      title: 'Aircraft Model',
      dataIndex: 'aircraft_model',
      key: 'aircraft_model',
    },
    {
      title: 'Total Revenue',
      dataIndex: 'total_revenue',
      key: 'total_revenue',
      render: (revenue) => `$${revenue.toFixed(2)}`, // Format as currency
    },
  ];

  return (
    <div className="admin-report">
      <h1 className="text-center font-bold mt-5 text-2xl">Total Revenue Generated By Aircrafts</h1>

      
      <div className="mt-8">
        <Table 
          columns={revenueColumns} 
          dataSource={revenueData} 
          rowKey="aircraft_model" 
          pagination={false} // Disable pagination for simplicity
          bordered
        />
      </div>

      
      <div className="mt-8">
        <ResponsiveContainer width="50%" height={400}>
          <BarChart 
            data={revenueData}  // Use revenue data for the chart
            margin={{ top: 20, right: 30, left: 20, bottom: 5 }}
          >
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="aircraft_model" label={{ value: 'Aircraft Model', position: 'insideBottomRight', offset: -10 }} />
            <YAxis label={{ value: 'Total Revenue ($)', angle: -90, position: 'insideLeft' }} />
            <Tooltip formatter={(value) => `$${value.toFixed(2)}`} />
            <Legend />
            <Bar dataKey="total_revenue" fill="black" name="Total Revenue" barSize={30} />
          </BarChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}
