import Aircraft from '../models/aircraftModel.js';

// Function to insert a new aircraft into the database
export const createAircraft = async (req, res) => {
  try {
    const aircraft_id = req.body.aircraft_id;
    const model = req.body.model; 
    console.log(aircraft_id, model);
    const aircraft = await Aircraft.createAircraft(aircraft_id, model);
    res.status(201).json(aircraft);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

export const getAllAircrafts = async (req, res) => {
  try {
    const aircraft = await Aircraft.getAircrafts();
    res.json(aircraft);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

export const getAircraftById = async (req, res) => {
  const { id } = req.params;
  console.log("Requesting aircraft with id: ", id);
  try {
    const aircraft = await Aircraft.getAircraftById(id);
    if (aircraft.length > 0) {
      res.json(aircraft[0]); // Assuming you're returning an array, send the first item
    } else {
      res.status(404).json({ message: 'Aircraft not found' });
    }
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

export const getModelById = async (req, res) => {
  const { aircraft_id } = req.params; // Correct destructuring
  console.log(aircraft_id);
  console.log("Requesting model with id: ", aircraft_id); // Log the correct id
  try {
    const model = await Aircraft.getModelById(aircraft_id); // Assuming Aircraft is your model or database query method
    if (model.length > 0) {
      res.json(model[0]); // Send the first item if found
    } else {
      res.status(404).json({ message: 'Model not found' });
    }
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

export const updateAircraft = async (req, res) => {  
  const { id } = req.params;
  const updates = req.body;
  try {
    const affectedRows = await Aircraft.updateAircraft(id, updates);
    if (affectedRows) {
      res.json({ message: 'Aircraft updated successfully' });
    } else {
      res.status(404).json({ message: 'Aircraft not found' });
    }
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

export const deleteAircraft = async (req, res) => {
  const { id } = req.params;
  try {
    const affectedRows = await Aircraft.deleteAircraft(id);
    if (affectedRows) {
      res.json({ message: 'Aircraft deleted successfully' });
    } else {
      res.status(404).json({ message: 'Aircraft not found' });
    }
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// Function to get total revenue generated by each Aircraft type
export const getAircraftRevenue = async (req, res) => {
  try {
    const revenue = await Aircraft.getRevenue();
    res.json(revenue);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};


