import Aircraft from '../models/aircraftModel.js';

// Function to insert a new aircraft into the database
export const createAircraft = async (req, res) => {
  try {
    const aircraft = await Aircraft.create(req.body);
    res.status(201).json(aircraft);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

export const getAllAircrafts = async (req, res) => {
  try {
    const aircraft = await Aircraft.getAll();
    res.json(aircraft);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

export const getAircraftById = async (req, res) => {
  const { id } = req.params;
  console.log("Requesting aircraft with id: ", id);
  try {
    const aircraft = await Aircraft.getById(id);
    if (aircraft) {
      res.json(aircraft);
    } else {
      res.status(404).json({ message: 'aircraft not found' });
    }
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

export const updateAircraft = async (req, res) => {  
  const { id } = req.params;
  const updates = req.body;
  try {
    const affectedRows = await Aircraft.update(id, updates);
    if (affectedRows) {
      res.json({ message: 'aircraft updated successfully' });
    } else {
      res.status(404).json({ message: 'aircraft not found' });
    }
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

export const deleteAircraft = async (req, res) => {
  const { id } = req.params;
  try {
    const affectedRows = await Aircraft.delete(id);
    if (affectedRows) {
      res.json({ message: 'aircraft deleted successfully' });
    } else {
      res.status(404).json({ message: 'aircraft not found' });
    }
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// Funcion to get total revenue generated by each Aircraft type
export const getAircraftRevenue = async (req, res) => {
  try {
    const revenue = await Aircraft.getAircraftRevenue();
    res.json(revenue);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};




